def get_process():

  # TODO: Load this data from a repository integrated with PostgreSQL
  return [
    {
      "id": 1,
      "type": "Americanas",
      "control": "TINTAS",
      "name": "TINTAS",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 502666358, "year": 2023}],
    },
    {
      "id": 2,
      "type": "Americanas",
      "control": "ti_Bacarina",
      "name": "Bacarina",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 3,
      "type": "Americanas",
      "control": "ti_Bailey",
      "name": "Bailey",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 587066, "year": 2023}],
    },
    {
      "id": 4,
      "type": "Americanas",
      "control": "ti_Bordo",
      "name": "Bordo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 154310837, "year": 2023}],
    },
    {
      "id": 5,
      "type": "Americanas",
      "control": "ti_Bourdin (S)",
      "name": "Bourdin (S)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 6,
      "type": "Americanas",
      "control": "ti_BRSCarmen",
      "name": "BRS Carmen",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 22242535, "year": 2023}],
    },
    {
      "id": 7,
      "type": "Americanas",
      "control": "ti_BRSCora",
      "name": "BRS Cora",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 19508450, "year": 2023}],
    },
    {
      "id": 8,
      "type": "Americanas",
      "control": "ti_BRS Magna",
      "name": "BRS Magna",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 13919693, "year": 2023}],
    },
    {
      "id": 9,
      "type": "Americanas",
      "control": "ti_BRS Margot",
      "name": "BRS Margot",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 36842, "year": 2023}],
    },
    {
      "id": 10,
      "type": "Americanas",
      "control": "ti_BRSMorena",
      "name": "BRS Morena",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 29,
      "type": "Americanas",
      "control": "ti_BRS Núbia ",
      "name": "BRS Núbia ",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 57060, "year": 2023}],
    },
    {
      "id": 11,
      "type": "Americanas",
      "control": "ti_BRS Rúbea",
      "name": "BRS Rúbea",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 3311843, "year": 2023}],
    },
    {
      "id": 12,
      "type": "Americanas",
      "control": "ti_BRSVioleta",
      "name": "BRS Violeta",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 15657282, "year": 2023}],
    },
    {
      "id": 13,
      "type": "Americanas",
      "control": "ti_BRS Vitória",
      "name": "BRS Vitória",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 8820, "year": 2023}],
    },
    {
      "id": 15,
      "type": "Americanas",
      "control": "ti_Champagnon(Champanheta)",
      "name": "Champagnon (Champanheta)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 16,
      "type": "Americanas",
      "control": "ti_Coleções",
      "name": "Coleções",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 17,
      "type": "Americanas",
      "control": "ti_Concord",
      "name": "Concord",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 25091503, "year": 2023}],
    },
    {
      "id": 18,
      "type": "Americanas",
      "control": "ti_Concordclone30",
      "name": "Concord clone 30",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 5491777, "year": 2023}],
    },
    {
      "id": 19,
      "type": "Americanas",
      "control": "ti_Couderc",
      "name": "Couderc",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 23121275, "year": 2023}],
    },
    {
      "id": 20,
      "type": "Americanas",
      "control": "ti_Cynthiana(1)",
      "name": "Cynthiana(1)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1186253, "year": 2023}],
    },
    {
      "id": 21,
      "type": "Americanas",
      "control": "ti_Herbemont",
      "name": "Herbemont",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1417502, "year": 2023}],
    },
    {
      "id": 22,
      "type": "Americanas",
      "control": "ti_IAC138022",
      "name": "IAC 138022",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 23,
      "type": "Americanas",
      "control": "ti_Isabel",
      "name": "Isabel",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 176590596, "year": 2023}],
    },
    {
      "id": 24,
      "type": "Americanas",
      "control": "ti_IsabelPrecoce",
      "name": "Isabel Precoce",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 17956434, "year": 2023}],
    },
    {
      "id": 25,
      "type": "Americanas",
      "control": "ti_Jacquez",
      "name": "Jacquez",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 12749029, "year": 2023}],
    },
    {
      "id": 26,
      "type": "Americanas",
      "control": "ti_Kyoko",
      "name": "Kyoko",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 27,
      "type": "Americanas",
      "control": "ti_Landot",
      "name": "Landot",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 28,
      "type": "Americanas",
      "control": "ti_Mistura de uvas americanas tinto",
      "name": "Mistura de uvas americanas tinto",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 346747, "year": 2023}],
    },
    {
      "id": 29,
      "type": "Americanas",
      "control": "ti_Oberlin",
      "name": "Oberlin",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 30,
      "type": "Americanas",
      "control": "ti_Othello",
      "name": "Othello",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 31,
      "type": "Americanas",
      "control": "ti_Paco",
      "name": "Paco",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 15300, "year": 2023}],
    },
    {
      "id": 32,
      "type": "Americanas",
      "control": "ti_Patricia",
      "name": "Patricia",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 33,
      "type": "Americanas",
      "control": "ti_Seibel",
      "name": "Seibel",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 2600315, "year": 2023}],
    },
    {
      "id": 34,
      "type": "Americanas",
      "control": "ti_Seibel2(seibeleto)",
      "name": "Seibel 2 (seibeleto)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 5387790, "year": 2023}],
    },
    {
      "id": 35,
      "type": "Americanas",
      "control": "ti_SeyveWillard(Tinta)",
      "name": "Seyve Willard (Tinta)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1002782, "year": 2023}],
    },
    {
      "id": 36,
      "type": "Americanas",
      "control": "ti_Vênus",
      "name": "Vênus",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 68626, "year": 2023}],
    },
    {
      "id": 37,
      "type": "Americanas",
      "control": "BRANCASEROSADAS",
      "name": "BRANCAS E ROSADAS",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 62577564, "year": 2023}],
    },
    {
      "id": 38,
      "type": "Americanas",
      "control": "br_Baco",
      "name": "Baco",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 39,
      "type": "Americanas",
      "control": "br_Bokay",
      "name": "Bokay",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 84670, "year": 2023}],
    },
    {
      "id": 40,
      "type": "Americanas",
      "control": "br_BRS Bibiana ",
      "name": "BRS Bibiana ",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 25491, "year": 2023}],
    },
    {
      "id": 41,
      "type": "Americanas",
      "control": "br_BRSClara",
      "name": "BRS Clara",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 42,
      "type": "Americanas",
      "control": "br_BRSLorena",
      "name": "BRS Lorena",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 10186931, "year": 2023}],
    },
    {
      "id": 43,
      "type": "Americanas",
      "control": "br_Couderc13",
      "name": "Couderc 13",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 4524468, "year": 2023}],
    },
    {
      "id": 44,
      "type": "Americanas",
      "control": "br_Delaware",
      "name": "Delaware",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 45,
      "type": "Americanas",
      "control": "br_DonaZillá",
      "name": "Dona Zillá",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 24890, "year": 2023}],
    },
    {
      "id": 46,
      "type": "Americanas",
      "control": "br_DutChess",
      "name": "Dut Chess",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 47,
      "type": "Americanas",
      "control": "br_Goethe",
      "name": "Goethe",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 269143, "year": 2023}],
    },
    {
      "id": 48,
      "type": "Americanas",
      "control": "br_IAC",
      "name": "IAC",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 49,
      "type": "Americanas",
      "control": "br_Juliana",
      "name": "Juliana",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 50,
      "type": "Americanas",
      "control": "br_Martha",
      "name": "Martha",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1380, "year": 2023}],
    },
    {
      "id": 51,
      "type": "Americanas",
      "control": "br_Mistura de uvas americanas",
      "name": "Mistura de uvas americanas",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 42550, "year": 2023}],
    },
    {
      "id": 52,
      "type": "Americanas",
      "control": "br_MoscatoEmbrapa",
      "name": "Moscato Embrapa",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 8790794, "year": 2023}],
    },
    {
      "id": 53,
      "type": "Americanas",
      "control": "br_Niagara",
      "name": "Niagara",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 54,
      "type": "Americanas",
      "control": "br_NiagaraBranca",
      "name": "Niagara Branca",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 23148433, "year": 2023}],
    },
    {
      "id": 55,
      "type": "Americanas",
      "control": "br_NiagaraRosada",
      "name": "Niagara Rosada",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 14987968, "year": 2023}],
    },
    {
      "id": 56,
      "type": "Americanas",
      "control": "br_Poloske",
      "name": "Poloske",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 55493, "year": 2023}],
    },
    {
      "id": 57,
      "type": "Americanas",
      "control": "br_Seleções",
      "name": "Seleções",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 58,
      "type": "Americanas",
      "control": "br_SeyveVillard",
      "name": "Seyve Villard",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 59,
      "type": "Americanas",
      "control": "br_SeyveVillard5276",
      "name": "Seyve Villard 5276",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 105771, "year": 2023}],
    },
    {
      "id": 60,
      "type": "Americanas",
      "control": "br_SeyveVillard12375",
      "name": "Seyve Villard 12375",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 329582, "year": 2023}],
    },
    {
      "id": 61,
      "type": "Americanas",
      "control": "br_TardiadeCaxias",
      "name": "Tardia de Caxias",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 62,
      "type": "Americanas",
      "control": "br_Outras",
      "name": "Outras(2)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 1,
      "type": "Mesa",
      "control": "TINTAS",
      "name": "TINTAS",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 175030, "year": 2023}],
    },
    {
      "id": 2,
      "type": "Mesa",
      "control": "ti_ Alphonse Lavallee",
      "name": " Alphonse Lavallee",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 3,
      "type": "Mesa",
      "control": "ti_ Moscato de Hamburgo",
      "name": " Moscato de Hamburgo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 175030, "year": 2023}],
    },
    {
      "id": 4,
      "type": "Mesa",
      "control": "BRANCAS",
      "name": "BRANCAS",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 13440, "year": 2023}],
    },
    {
      "id": 5,
      "type": "Mesa",
      "control": "br_Cardinal",
      "name": " Cardinal",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 6,
      "type": "Mesa",
      "control": "br_Golden Queen",
      "name": " Golden Queen",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 7,
      "type": "Mesa",
      "control": "br_Patrícia",
      "name": " Patrícia",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 8,
      "type": "Mesa",
      "control": "br_Perlona",
      "name": " Perlona",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 9,
      "type": "Mesa",
      "control": "br_Italia",
      "name": " Italia",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 10,
      "type": "Mesa",
      "control": "br_Rubi (Itália, Itália Ro)",
      "name": " Rubi (Itália, Itália Ro)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 13440, "year": 2023}],
    },
    {
      "id": 1,
      "type": "SemClass",
      "control": "sc",
      "name": "Sem classificação",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 1,
      "type": "Viniferas",
      "control": "TINTAS",
      "name": "TINTAS",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 2,
      "type": "Viniferas",
      "control": "ti_Alicante Bouschet",
      "name": "Alicante Bouschet",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 3,
      "type": "Viniferas",
      "control": "ti_Ancelota",
      "name": "Ancelota",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 4,
      "type": "Viniferas",
      "control": "ti_Aramon",
      "name": "Aramon",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 5,
      "type": "Viniferas",
      "control": "ti_Alfrocheiro",
      "name": "Alfrocheiro",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 6,
      "type": "Viniferas",
      "control": "ti_Arinarnoa",
      "name": "Arinarnoa",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 7,
      "type": "Viniferas",
      "control": "ti_Aspirant Bouschet",
      "name": "Aspirant Bouschet",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 138338, "year": 2023}],
    },
    {
      "id": 8,
      "type": "Viniferas",
      "control": "ti_Barbera",
      "name": "Barbera",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 35292, "year": 2023}],
    },
    {
      "id": 9,
      "type": "Viniferas",
      "control": "ti_Bonarda",
      "name": "Bonarda",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 7800, "year": 2023}],
    },
    {
      "id": 10,
      "type": "Viniferas",
      "control": "ti_Cabernet Franc",
      "name": "Cabernet Franc",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 11,
      "type": "Viniferas",
      "control": "ti_Cabernet Sauvignon",
      "name": "Cabernet Sauvignon",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 12,
      "type": "Viniferas",
      "control": "ti_ Caladoc",
      "name": "Caladoc",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 8310, "year": 2023}],
    },
    {
      "id": 13,
      "type": "Viniferas",
      "control": "ti_Campanario",
      "name": "Campanario",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 14,
      "type": "Viniferas",
      "control": "ti_Canaiolo",
      "name": "Canaiolo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 15,
      "type": "Viniferas",
      "control": "ti_Carignan",
      "name": "Carignan",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 16,
      "type": "Viniferas",
      "control": "ti_Carmenere",
      "name": "Carmenere",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 17,
      "type": "Viniferas",
      "control": "ti_Castelão",
      "name": "Castelão",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 18,
      "type": "Viniferas",
      "control": "ti_Corvina",
      "name": "Corvina",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 2200, "year": 2023}],
    },
    {
      "id": 19,
      "type": "Viniferas",
      "control": "ti_Croatina",
      "name": "Croatina",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 20,
      "type": "Viniferas",
      "control": "ti_Cinsaut",
      "name": "Cinsaut",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 21,
      "type": "Viniferas",
      "control": "ti_Dom Felder",
      "name": "Dom Felder",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 22,
      "type": "Viniferas",
      "control": "ti_Dolcetto",
      "name": "Dolcetto",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 23,
      "type": "Viniferas",
      "control": "ti_Durif",
      "name": "Durif",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 24,
      "type": "Viniferas",
      "control": "ti_Egiodola",
      "name": "Egiodola",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 25,
      "type": "Viniferas",
      "control": "ti_Ekigaina",
      "name": "Ekigaina",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1000, "year": 2023}],
    },
    {
      "id": 26,
      "type": "Viniferas",
      "control": "ti_Festival (Sugraone)",
      "name": "Festival (Sugraone)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 27,
      "type": "Viniferas",
      "control": "ti_Franconia",
      "name": "Franconia",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 28,
      "type": "Viniferas",
      "control": "ti_Freisa",
      "name": "Freisa",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 29,
      "type": "Viniferas",
      "control": "ti_Gamay St Romain",
      "name": "Gamay St Romain",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 30,
      "type": "Viniferas",
      "control": "ti_Gamay Beaujolais",
      "name": "Gamay Beaujolais",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 126667, "year": 2023}],
    },
    {
      "id": 31,
      "type": "Viniferas",
      "control": "ti_Grand Noir",
      "name": "Grand Noir",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 32,
      "type": "Viniferas",
      "control": "ti_Grenache",
      "name": "Grenache",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 830, "year": 2023}],
    },
    {
      "id": 33,
      "type": "Viniferas",
      "control": "ti_Jaen",
      "name": "Jaen",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 34,
      "type": "Viniferas",
      "control": "ti_Lagrein",
      "name": "Lagrein",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 3100, "year": 2023}],
    },
    {
      "id": 35,
      "type": "Viniferas",
      "control": "ti_Lambrusco",
      "name": "Lambrusco",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 15620, "year": 2023}],
    },
    {
      "id": 36,
      "type": "Viniferas",
      "control": "ti_Malbec",
      "name": "Malbec",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 37,
      "type": "Viniferas",
      "control": "ti_Marzemina",
      "name": "Marzemina",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 390, "year": 2023}],
    },
    {
      "id": 38,
      "type": "Viniferas",
      "control": "ti_Merlot",
      "name": "Merlot",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 39,
      "type": "Viniferas",
      "control": "ti_Marselan",
      "name": "Marselan",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 40,
      "type": "Viniferas",
      "control": "ti_Mistura de uvas viníferas tinto ",
      "name": "Mistura de uvas viníferas tinto ",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 700, "year": 2023}],
    },
    {
      "id": 41,
      "type": "Viniferas",
      "control": "ti_Molinera",
      "name": "Molinera",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 2600, "year": 2023}],
    },
    {
      "id": 42,
      "type": "Viniferas",
      "control": "ti_Montepulciano",
      "name": "Montepulciano",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 42503, "year": 2023}],
    },
    {
      "id": 43,
      "type": "Viniferas",
      "control": "ti_Moscato Bailey",
      "name": "Moscato Bailey",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 44,
      "type": "Viniferas",
      "control": "ti_Napa Gamay",
      "name": "Napa Gamay",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 45,
      "type": "Viniferas",
      "control": "ti_Nebbiolo",
      "name": "Nebbiolo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 26788, "year": 2023}],
    },
    {
      "id": 46,
      "type": "Viniferas",
      "control": "ti_Petit Verdot",
      "name": "Petit Verdot",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 207896, "year": 2023}],
    },
    {
      "id": 47,
      "type": "Viniferas",
      "control": "ti_Petite Sirah",
      "name": "Petite Sirah",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 48,
      "type": "Viniferas",
      "control": "ti_Pinotage",
      "name": "Pinotage",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 397456, "year": 2023}],
    },
    {
      "id": 49,
      "type": "Viniferas",
      "control": "ti_Pinot Noir",
      "name": "Pinot Noir",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 50,
      "type": "Viniferas",
      "control": "ti_Pinot Saint George",
      "name": "Pinot Saint George",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 5060, "year": 2023}],
    },
    {
      "id": 51,
      "type": "Viniferas",
      "control": "ti_Piriquita",
      "name": "Piriquita",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 52,
      "type": "Viniferas",
      "control": "ti_Primitivo",
      "name": "Primitivo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1650, "year": 2023}],
    },
    {
      "id": 53,
      "type": "Viniferas",
      "control": "ti_Rebo",
      "name": "Rebo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 330784, "year": 2023}],
    },
    {
      "id": 54,
      "type": "Viniferas",
      "control": "ti_Refosco",
      "name": "Refosco",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 55,
      "type": "Viniferas",
      "control": "ti_Rondinella",
      "name": "Rondinella",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 5280, "year": 2023}],
    },
    {
      "id": 56,
      "type": "Viniferas",
      "control": "ti_Ruby Cabernet",
      "name": "Ruby Cabernet",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 163069, "year": 2023}],
    },
    {
      "id": 57,
      "type": "Viniferas",
      "control": "ti_Sangiovese",
      "name": "Sangiovese",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 92540, "year": 2023}],
    },
    {
      "id": 58,
      "type": "Viniferas",
      "control": "ti_Saperavi ",
      "name": "Saperavi ",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 13323, "year": 2023}],
    },
    {
      "id": 59,
      "type": "Viniferas",
      "control": "ti_Sira (falsa)",
      "name": "Sira (falsa)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 60,
      "type": "Viniferas",
      "control": "ti_Tannat",
      "name": "Tannat",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 61,
      "type": "Viniferas",
      "control": "ti_Tempranillo",
      "name": "Tempranillo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 375165, "year": 2023}],
    },
    {
      "id": 62,
      "type": "Viniferas",
      "control": "ti_Teroldego",
      "name": "Teroldego",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 63,
      "type": "Viniferas",
      "control": "ti_Torrontes",
      "name": "Torrontes",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 23500, "year": 2023}],
    },
    {
      "id": 64,
      "type": "Viniferas",
      "control": "ti_Tinta Barroca",
      "name": "Tinta Barroca",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 65,
      "type": "Viniferas",
      "control": "ti_Tinta Roriz ",
      "name": "Tinta Roriz ",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 3006, "year": 2023}],
    },
    {
      "id": 66,
      "type": "Viniferas",
      "control": "ti_Touriga Francesa",
      "name": "Touriga Francesa",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 67,
      "type": "Viniferas",
      "control": "ti_Touriga Nacional",
      "name": "Touriga Nacional",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 171866, "year": 2023}],
    },
    {
      "id": 68,
      "type": "Viniferas",
      "control": "ti_Tinta Madeira",
      "name": "Tinta Madeira",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 69,
      "type": "Viniferas",
      "control": "ti_Tintoria",
      "name": "Tintoria",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 70,
      "type": "Viniferas",
      "control": "ti_Trincdeira",
      "name": "Trincdeira",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 71,
      "type": "Viniferas",
      "control": "ti_Trousseau",
      "name": "Trousseau",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 72,
      "type": "Viniferas",
      "control": "ti_Zinfandel",
      "name": "Zinfandel",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 73,
      "type": "Viniferas",
      "control": "ti_Outras1",
      "name": "Outras1",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 74,
      "type": "Viniferas",
      "control": "BRANCASEROSADAS",
      "name": "BRANCAS E ROSADAS",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 75,
      "type": "Viniferas",
      "control": "br_Aliatico",
      "name": "Aliatico",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 76,
      "type": "Viniferas",
      "control": "br_Aligote",
      "name": "Aligote",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 77,
      "type": "Viniferas",
      "control": "br_Altesse",
      "name": "Altesse",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 78,
      "type": "Viniferas",
      "control": "br_Alvarinho",
      "name": "Alvarinho",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 150467, "year": 2023}],
    },
    {
      "id": 79,
      "type": "Viniferas",
      "control": "br_Arriloba",
      "name": "Arriloba",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 80,
      "type": "Viniferas",
      "control": "br_Auxerrois",
      "name": "Auxerrois",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 81,
      "type": "Viniferas",
      "control": "br_Burger",
      "name": "Burger",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 82,
      "type": "Viniferas",
      "control": "br_Chardonnay",
      "name": "Chardonnay",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 83,
      "type": "Viniferas",
      "control": "br_Chasselas",
      "name": "Chasselas",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 84,
      "type": "Viniferas",
      "control": "br_Chenin Blanc",
      "name": "Chenin Blanc",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 298406, "year": 2023}],
    },
    {
      "id": 85,
      "type": "Viniferas",
      "control": "br_Clairette(1)",
      "name": "Clairette(1)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 86,
      "type": "Viniferas",
      "control": "br_Colombard",
      "name": "Colombard",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 87,
      "type": "Viniferas",
      "control": "br_Flora",
      "name": "Flora",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 88,
      "type": "Viniferas",
      "control": "br_Garganega",
      "name": "Garganega",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 400, "year": 2023}],
    },
    {
      "id": 89,
      "type": "Viniferas",
      "control": "br_Gewurztraminer",
      "name": "Gewurztraminer",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 239070, "year": 2023}],
    },
    {
      "id": 90,
      "type": "Viniferas",
      "control": "br_Gouveio",
      "name": "Gouveio",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 91,
      "type": "Viniferas",
      "control": "br_Gros Manseng",
      "name": "Gros Manseng",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 4510, "year": 2023}],
    },
    {
      "id": 92,
      "type": "Viniferas",
      "control": "br_Italia (Pirovano 65) (PE)",
      "name": "Italia (Pirovano 65) (PE)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 10350, "year": 2023}],
    },
    {
      "id": 93,
      "type": "Viniferas",
      "control": "br_Maccabeo",
      "name": "Maccabeo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 94,
      "type": "Viniferas",
      "control": "br_Malvasia",
      "name": "Malvasia",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 95,
      "type": "Viniferas",
      "control": "br_Malvasia Amarela",
      "name": "Malvasia Amarela",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 67467, "year": 2023}],
    },
    {
      "id": 96,
      "type": "Viniferas",
      "control": "br_Malvasia Bianca",
      "name": "Malvasia Bianca",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 97,
      "type": "Viniferas",
      "control": "br_Malvasia Chianti",
      "name": "Malvasia Chianti",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 98,
      "type": "Viniferas",
      "control": "br_Malvasia Verde",
      "name": "Malvasia Verde",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 46510, "year": 2023}],
    },
    {
      "id": 99,
      "type": "Viniferas",
      "control": "br_Malvasia di Candia",
      "name": "Malvasia di Candia",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 100,
      "type": "Viniferas",
      "control": "br_Malvasia Istriana",
      "name": "Malvasia Istriana",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 101,
      "type": "Viniferas",
      "control": "br_Mistura de uvas viníferas",
      "name": "Mistura de uvas viníferas branco",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 41078, "year": 2023}],
    },
    {
      "id": 102,
      "type": "Viniferas",
      "control": "br_Mistura de uvas viníferas",
      "name": "Mistura de uvas viníferas rosado",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1100, "year": 2023}],
    },
    {
      "id": 103,
      "type": "Viniferas",
      "control": "br_Moscato_branco",
      "name": "Moscato Branco",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 104,
      "type": "Viniferas",
      "control": "br_Moscato Canelli",
      "name": "Moscato Canelli",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 105,
      "type": "Viniferas",
      "control": "br_Moscato Giallo",
      "name": "Moscato Giallo",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 106,
      "type": "Viniferas",
      "control": "br_Moscato Nazareno",
      "name": "Moscato Nazareno",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 504982, "year": 2023}],
    },
    {
      "id": 107,
      "type": "Viniferas",
      "control": "br_Moscato Bianco R2",
      "name": "Moscato Bianco R2",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 108,
      "type": "Viniferas",
      "control": "br_Moscato de Alexandria",
      "name": "Moscato de Alexandria",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 404111, "year": 2023}],
    },
    {
      "id": 109,
      "type": "Viniferas",
      "control": "br_Moscato Rosado",
      "name": "Moscato Rosado",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 900, "year": 2023}],
    },
    {
      "id": 110,
      "type": "Viniferas",
      "control": "br_Muscat a Petits Grains",
      "name": "Muscat à Petits Grains",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 6000, "year": 2023}],
    },
    {
      "id": 111,
      "type": "Viniferas",
      "control": "br_Muller Thurgau",
      "name": "Muller Thurgau",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 112,
      "type": "Viniferas",
      "control": "br_Muscadelle",
      "name": "Muscadelle",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 113,
      "type": "Viniferas",
      "control": "br_Ora",
      "name": "Ora",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 114,
      "type": "Viniferas",
      "control": "br_Palomino",
      "name": "Palomino",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 115,
      "type": "Viniferas",
      "control": "br_Petit Manseng",
      "name": "Petit Manseng",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 3915, "year": 2023}],
    },
    {
      "id": 116,
      "type": "Viniferas",
      "control": "br_Peverella",
      "name": "Peverella",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 45898, "year": 2023}],
    },
    {
      "id": 117,
      "type": "Viniferas",
      "control": "br_Pinot Blanc",
      "name": "Pinot Blanc",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 1310, "year": 2023}],
    },
    {
      "id": 118,
      "type": "Viniferas",
      "control": "br_Pinot Gris",
      "name": "Pinot Gris",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 178683, "year": 2023}],
    },
    {
      "id": 119,
      "type": "Viniferas",
      "control": "br_Prosecco",
      "name": "Prosecco",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 120,
      "type": "Viniferas",
      "control": "br_Red Veltliner",
      "name": "Red Veltliner",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 121,
      "type": "Viniferas",
      "control": "br_Riesling Italico",
      "name": "Riesling Italico",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 122,
      "type": "Viniferas",
      "control": "br_Riesling Renano",
      "name": "Riesling Renano",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 123,
      "type": "Viniferas",
      "control": "br_Sauvignon Blanc(2)",
      "name": "Sauvignon Blanc(2)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 124,
      "type": "Viniferas",
      "control": "br_Sauvignon Gris",
      "name": "Sauvignon Gris",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 125,
      "type": "Viniferas",
      "control": "br_Seara Nova",
      "name": "Seara Nova",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 126,
      "type": "Viniferas",
      "control": "br_Semillon",
      "name": "Semillon",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 112905, "year": 2023}],
    },
    {
      "id": 127,
      "type": "Viniferas",
      "control": "br_Schonburger",
      "name": "Schonburger",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 12687, "year": 2023}],
    },
    {
      "id": 128,
      "type": "Viniferas",
      "control": "br_Sylvaner",
      "name": "Sylvaner",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 2342, "year": 2023}],
    },
    {
      "id": 129,
      "type": "Viniferas",
      "control": "br_Tocai Friulano",
      "name": "Tocai Friulano",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 6150, "year": 2023}],
    },
    {
      "id": 130,
      "type": "Viniferas",
      "control": "br_Trebbiano",
      "name": "Trebbiano",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 131,
      "type": "Viniferas",
      "control": "br_Trebbiano Toscano",
      "name": "Trebbiano Toscano",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 139845, "year": 2023}],
    },
    {
      "id": 132,
      "type": "Viniferas",
      "control": "br_Verdea",
      "name": "Verdea",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 133,
      "type": "Viniferas",
      "control": "br_Verdelho",
      "name": "Verdelho",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 2080, "year": 2023}],
    },
    {
      "id": 134,
      "type": "Viniferas",
      "control": "br_Verdiso",
      "name": "Verdiso",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 135,
      "type": "Viniferas",
      "control": "br_Vermentino",
      "name": "Vermentino",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 28218, "year": 2023}],
    },
    {
      "id": 136,
      "type": "Viniferas",
      "control": "br_Vernaccia",
      "name": "Vernaccia",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 800, "year": 2023}],
    },
    {
      "id": 137,
      "type": "Viniferas",
      "control": "br_Viogner ",
      "name": "Viogner ",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 138,
      "type": "Viniferas",
      "control": "br_Viognier",
      "name": "Viognier",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
    {
      "id": 139,
      "type": "Viniferas",
      "control": "br_Outras(3)",
      "name": "Outras(3)",
      "type": "Outro",
      "quantities": [{"unit": "kg", "quantity": 0, "year": 2023}],
    },
  ]
